#!/bin/sh
#
# Start adb....
#

case "$1" in
  start)
	echo "Starting wifi..."
	/sbin/wifi_connect.sh &
	;;
  stop)
	;;
  restart|reload)
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
