obj-$(CONFIG_DEFAULT_BATTERY_CV)	+= pwm-battery-cv.o
obj-$(CONFIG_ILOCK_BATTERY_CV)	+= ilock-battery-cv.o
obj-$(CONFIG_MS800_BATTERY_CV)	+= ms800-battery-cv.o
obj-$(CONFIG_BEETHOVEN_CMD_BATTERY_CV)	+= beethoven-cmd-battery-cv.o
