
obj-$(CONFIG_PRODUCT_X1000_PHOENIX)		+= phoenix/
obj-$(CONFIG_PRODUCT_X1000_HALLEY2)		+= halley2/
obj-$(CONFIG_PRODUCT_X1000_ATHENA_EYES)		+= athena_eyes/
obj-$(CONFIG_PRODUCT_X1000_SOLAR)		+= solar/
obj-$(CONFIG_PRODUCT_X1000_IDRIVER)             += idriver/
obj-$(CONFIG_PRODUCT_X1000_SPEAKER)             += speaker/
obj-$(CONFIG_PRODUCT_X1000_BEETHOVEN)             += beethoven/
obj-$(CONFIG_PRODUCT_X1000_SKYWORTH)             += skyworth/
obj-$(CONFIG_PRODUCT_X1000_ILOCK)             += ilock/
obj-$(CONFIG_PRODUCT_X1000_MS800)             += ms800/
