#
# Makefile for the input misc drivers.
#

# Each configuration option enables a list of files.

obj-y  += byd_fps_bf663x.o  byd_fps_platform.o byd_fps_gesture_detect.o byd_fps_timer.o byd_fps_wakeup.o byd_fps_spi.o byd_fps_lib_fps22.o byd_fingerprint.o

#obj-m := byd.o
#byd-objs := byd_fps_bf663x.o  byd_fps_platform.o byd_fps_gesture_detect.o byd_fps_timer.o byd_fps_wakeup.o byd_fps_spi.o byd_fps_lib_fps22.o byd_fingerprint.o

