#!/bin/bash
rm -rf out/$TARGET_DEVICE/system/init
rm -rf out/$TARGET_DEVICE/system/etc
rm -rf out/$TARGET_DEVICE/system/bin
rm -rf out/$TARGET_DEVICE/system/sbin
rm -rf out/$TARGET_DEVICE/system/lib
rm -rf out/$TARGET_DEVICE/system/libexec
rm -rf out/$TARGET_DEVICE/system/tmp
rm -rf out/$TARGET_DEVICE/system/var
rm -rf out/$TARGET_DEVICE/system/usr/bin
rm -rf out/$TARGET_DEVICE/system/usr/sbin
rm -rf out/$TARGET_DEVICE/system/usr/lib/libdbus-1.so
rm -rf out/$TARGET_DEVICE/system/usr/lib/libdbus-1.so.3
rm -rf out/$TARGET_DEVICE/system/usr/lib/libdbus-1.so.3.14.9
rm -rf out/$TARGET_DEVICE/system/usr/lib/libnl-cli-3.so
rm -rf out/$TARGET_DEVICE/system/usr/lib/libnl-cli-3.so.200
rm -rf out/$TARGET_DEVICE/system/usr/lib/libnl-cli-3.so.200.20.0
rm -rf out/$TARGET_DEVICE/system/usr/lib/libnl-idiag-3.so
rm -rf out/$TARGET_DEVICE/system/usr/lib/libnl-idiag-3.so.200
rm -rf out/$TARGET_DEVICE/system/usr/lib/libnl-idiag-3.so.200.20.0
rm -rf out/$TARGET_DEVICE/system/usr/lib/libnl-nf-3.so
rm -rf out/$TARGET_DEVICE/system/usr/lib/libnl-nf-3.so.200
rm -rf out/$TARGET_DEVICE/system/usr/lib/libnl-nf-3.so.200.20.0
rm -rf out/$TARGET_DEVICE/system/usr/lib/libnl-route-3.so
rm -rf out/$TARGET_DEVICE/system/usr/lib/libnl-route-3.so.200
rm -rf out/$TARGET_DEVICE/system/usr/lib/libnl-route-3.so.200.20.0
rm -rf out/$TARGET_DEVICE/system/usr/lib/libsha1.so.0
rm -rf out/$TARGET_DEVICE/system/usr/lib/libsha1.so.0.0.0
rm -rf out/$TARGET_DEVICE/system/usr/lib/libss.so
rm -rf out/$TARGET_DEVICE/system/usr/lib/libss.so.2
rm -rf out/$TARGET_DEVICE/system/usr/lib/libss.so.2.0
rm -rf out/$TARGET_DEVICE/system/usr/lib/libuuid.so
rm -rf out/$TARGET_DEVICE/system/usr/lib/terminfo
rm -rf out/$TARGET_DEVICE/system/usr/libexec
rm -rf out/$TARGET_DEVICE/system/usr/share
