
obj-$(CONFIG_LCD_TRULY_TFT240240_2_E) += lcd-truly_tft240240_2_e.o
obj-$(CONFIG_LCD_DK_ST7789H2) += dk_st7789h2.o
obj-$(CONFIG_LCD_ZK_ST7789V)           += zk_st7789v.o
obj-$(CONFIG_LCD_UG2864HLBEG01)         += ug2864hlbeg01.o
obj-$(CONFIG_TFT_FRD397BP4511)			+= frd397bp4511.o
