obj-$(CONFIG_INPUT_BYD_FPS_SPI)				+= byd/
obj-$(CONFIG_FINGERPRINT_MICROARRAY)		+= microarray_fp.o
obj-$(CONFIG_FINGERPRINT_GOODIX_GF5X)		+= spi-goodix-gf5xxx.o
obj-$(CONFIG_FINGERPRINT_FPC)				+= fpc_fp.o